"""mark-mark-types

Revision ID: 1716e00dd644
Revises: cebaebdb71a3
Create Date: 2026-08-06 21:27:17.574373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1716e00dd644'
down_revision: Union[str, Sequence[str], None] = 'cebaebdb71a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'mark_types', ['mark_type_name'])
    op.add_column('marks', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('marks', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marks', 'updated_at')
    op.drop_column('marks', 'created_at')
    op.drop_constraint(None, 'mark_types', type_='unique')
    # ### end Alembic commands ###
