"""school-year-period

Revision ID: 1a9c26943c18
Revises: 30105138271d
Create Date: 2026-07-24 12:44:16.699097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a9c26943c18'
down_revision: Union[str, Sequence[str], None] = '30105138271d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subjectName', sa.String(), nullable=False),
    sa.Column('domaine', sa.Enum('LITTERATURE', 'SCIENCE', 'RELIGION', 'OTHER', name='domaineenum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subjects_id'), 'subjects', ['id'], unique=False)
    op.create_index(op.f('ix_subjects_subjectName'), 'subjects', ['subjectName'], unique=True)
    op.create_table('class_subject_association',
    sa.Column('school_class_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('hours_per_week', sa.Integer(), nullable=True),
    sa.Column('coefficient', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['period_id'], ['periods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_class_id'], ['school_classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('school_class_id', 'subject_id', 'period_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('class_subject_association')
    op.drop_index(op.f('ix_subjects_subjectName'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_id'), table_name='subjects')
    op.drop_table('subjects')
    # ### end Alembic commands ###
