"""school-year-period

Revision ID: 30105138271d
Revises: aa9542d9d7b4
Create Date: 2026-07-24 10:35:16.346315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30105138271d'
down_revision: Union[str, Sequence[str], None] = 'aa9542d9d7b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school_years',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('startYear', sa.Integer(), nullable=False),
    sa.Column('endYear', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_school_years_id'), 'school_years', ['id'], unique=False)
    op.create_index(op.f('ix_school_years_name'), 'school_years', ['name'], unique=True)
    op.create_table('periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('periodName', sa.String(), nullable=False),
    sa.Column('schoolYear_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['schoolYear_id'], ['school_years.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_periods_id'), 'periods', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_periods_id'), table_name='periods')
    op.drop_table('periods')
    op.drop_index(op.f('ix_school_years_name'), table_name='school_years')
    op.drop_index(op.f('ix_school_years_id'), table_name='school_years')
    op.drop_table('school_years')
    # ### end Alembic commands ###
