"""mark-mark-types

Revision ID: cebaebdb71a3
Revises: 194d3c38d039
Create Date: 2026-08-05 13:43:28.756644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cebaebdb71a3'
down_revision: Union[str, Sequence[str], None] = '194d3c38d039'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mark_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mark_type_name', sa.String(length=50), nullable=False),
    sa.Column('coefficient', sa.Float(), nullable=False),
    sa.Column('is_by_subject', sa.Boolean(), nullable=False),
    sa.Column('is_by_period', sa.Boolean(), nullable=False),
    sa.Column('is_annual', sa.Boolean(), nullable=False),
    sa.Column('is_inserted', sa.Boolean(), nullable=False),
    sa.Column('used_to_calculate', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['used_to_calculate'], ['mark_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('mark_type_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('period_id', sa.Integer(), nullable=True),
    sa.Column('school_class_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mark_type_id'], ['mark_types.id'], ),
    sa.ForeignKeyConstraint(['period_id'], ['periods.id'], ),
    sa.ForeignKeyConstraint(['school_class_id'], ['school_classes.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('marks')
    op.drop_table('mark_types')
    # ### end Alembic commands ###
